Repository Ajou-Connect/OneBoard-Server, pull requests merged in 2021-11, with the labels that each got.

#4 Shy/setting/test db separation
  .gitignore
  src/main/resources/application.properties
Labels: enhancement

#10 Refactor class name
  src/main/java/com/connect/oneboardserver/service/lecture/notice/NoticeService.java
  src/main/java/com/connect/oneboardserver/web/dto/ResponseDto.java
  src/main/java/com/connect/oneboardserver/web/lecture/notice/NoticeApiController.java
  src/main/java/com/connect/oneboardserver/web/login/MemberApiController.java
  src/test/java/com/connect/oneboardserver/web/lecture/notice/NoticeApiControllerTest.java
Labels: Refactoring

#13 Shy/feature/lecture/lecture
  src/main/java/com/connect/oneboardserver/service/lecture/LectureService.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/LectureFindAllResponseDto.java
Labels: enhancement

#15 Kmj/feature/assignment
  src/main/java/com/connect/oneboardserver/domain/assignment/Assignment.java
  src/main/java/com/connect/oneboardserver/domain/assignment/AssignmentRepository.java
  src/main/java/com/connect/oneboardserver/domain/assignment/Submit.java
  src/main/java/com/connect/oneboardserver/domain/assignment/SubmitRepository.java
  src/main/java/com/connect/oneboardserver/service/assignment/AssignmentFileService.java
  src/main/java/com/connect/oneboardserver/service/assignment/AssignmentService.java
  src/main/java/com/connect/oneboardserver/service/assignment/SubmitService.java
  src/main/java/com/connect/oneboardserver/web/CustomErrorController.java
  src/main/java/com/connect/oneboardserver/web/assignment/AssignmentApiController.java
  src/main/java/com/connect/oneboardserver/web/assignment/SubmitApiController.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentCreateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentListFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentUpdateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/SubmitCheckRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/SubmitCreateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/SubmitFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/SubmitResponseDto.java
  src/main/java/com/connect/oneboardserver/web/login/MemberApiController.java
  src/test/java/com/connect/oneboardserver/domain/assignment/AssignmentRepositoryTest.java
  src/test/java/com/connect/oneboardserver/web/assignment/AssignmentApiControllerTest.java
Labels: enhancement

#16 Resolve assignment list issue
  src/main/java/com/connect/oneboardserver/service/assignment/AssignmentService.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentFindResponseDto.java
Labels: bug

#22 Update assignment feature
  src/main/java/com/connect/oneboardserver/domain/assignment/Assignment.java
  src/main/java/com/connect/oneboardserver/domain/assignment/Submit.java
  src/main/java/com/connect/oneboardserver/domain/assignment/SubmitRepository.java
  src/main/java/com/connect/oneboardserver/service/assignment/AssignmentService.java
  src/main/java/com/connect/oneboardserver/service/assignment/SubmitService.java
  src/main/java/com/connect/oneboardserver/web/assignment/SubmitApiController.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentCreateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentUpdateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/SubmitCheckRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/SubmitFindResponseDto.java
Labels: enhancement

#24 Shy/feature/attendance
  src/main/java/com/connect/oneboardserver/domain/attendance/Attendance.java
  src/main/java/com/connect/oneboardserver/domain/attendance/AttendanceRepository.java
  src/main/java/com/connect/oneboardserver/domain/lecture/Lecture.java
  src/main/java/com/connect/oneboardserver/domain/lecture/lesson/Lesson.java
  src/main/java/com/connect/oneboardserver/service/attendance/AttendanceService.java
  src/main/java/com/connect/oneboardserver/service/lecture/LessonService.java
  src/main/java/com/connect/oneboardserver/web/attendance/AttendanceApiController.java
  src/main/java/com/connect/oneboardserver/web/dto/attendance/AttendFindAllForStuResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/attendance/AttendFindForStuDto.java
  src/main/java/com/connect/oneboardserver/web/dto/attendance/AttendanceUpdateAllRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/attendance/AttendanceUpdateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/LessonCreateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/LessonFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/LessonListFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/LessonUpdateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/notice/NoticeCreateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/notice/NoticeCreateResponseDto.java
  src/test/java/com/connect/oneboardserver/domain/attendance/AttendanceRepositoryTest.java
  src/test/java/com/connect/oneboardserver/domain/lesson/LessonRepositoryTest.java
  src/test/java/com/connect/oneboardserver/web/attendance/AttendanceApiControllerTest.java
  src/test/java/com/connect/oneboardserver/web/lecture/LessonApiControllerTest.java
  src/test/java/com/connect/oneboardserver/web/lecture/NoticeApiControllerTest.java
Labels: enhancement

#27 Kmj/feature/assignment
  src/main/java/com/connect/oneboardserver/domain/assignment/Submit.java
  src/main/java/com/connect/oneboardserver/domain/assignment/SubmitRepository.java
  src/main/java/com/connect/oneboardserver/domain/grade/Grade.java
  src/main/java/com/connect/oneboardserver/domain/grade/GradeRatio.java
  src/main/java/com/connect/oneboardserver/domain/grade/GradeRatioRepository.java
  src/main/java/com/connect/oneboardserver/domain/grade/GradeRepository.java
  src/main/java/com/connect/oneboardserver/domain/relation/GradeRatioLecture.java
  src/main/java/com/connect/oneboardserver/domain/relation/GradeRatioLectureRepository.java
  src/main/java/com/connect/oneboardserver/domain/relation/MemberLectureRepository.java
  src/main/java/com/connect/oneboardserver/service/assignment/SubmitService.java
  src/main/java/com/connect/oneboardserver/service/grade/GradeRatioService.java
  src/main/java/com/connect/oneboardserver/service/grade/GradeService.java
  src/main/java/com/connect/oneboardserver/web/assignment/SubmitApiController.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/AssignmentFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/SubmitFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/assignment/SubmitUpdateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/grade/GradeRatioCreateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/grade/GradeRatioFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/grade/GradeRatioResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/grade/GradeRatioUpdateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/grade/GradeApiController.java
  src/main/java/com/connect/oneboardserver/web/grade/GradeRatioApiController.java
  src/test/java/com/connect/oneboardserver/domain/grade/GradeRatioRepositoryTest.java
  src/test/java/com/connect/oneboardserver/domain/grade/GradeRepositoryTest.java
  src/test/java/com/connect/oneboardserver/web/grade/GradeRatioApiControllerTest.java
Labels: enhancement

#32 Pmw/feature/lesson/note4
  src/main/java/com/connect/oneboardserver/domain/lecture/lesson/Lesson.java
  src/main/java/com/connect/oneboardserver/service/lecture/LessonService.java
  src/main/java/com/connect/oneboardserver/service/lecture/NoteService.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/LessonCreateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/LessonFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/LessonListFindResponseDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/LessonUpdateRequestDto.java
  src/main/java/com/connect/oneboardserver/web/dto/lecture/lesson/note/NoteUploadResponseDto.java
  src/main/java/com/connect/oneboardserver/web/lecture/NoteApiController.java
  src/test/java/com/connect/oneboardserver/domain/lesson/LessonRepositoryTest.java
  src/test/java/com/connect/oneboardserver/web/lecture/LessonApiControllerTest.java
Labels: enhancement
